org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.173
loader_version_range=[4,)

mod_version=0.2.10-alpha-neoforge
maven_group=me.cortex
archives_base_name=voxy
mod_id=voxy

parchment_mc=1.21.1
parchment_version=2024.11.17
