modLoader="javafml"
loaderVersion="[1,)"
license="All-Rights-Reserved"
issueTrackerURL="https://github.com/Ameisin/voxy_ports/issues"

[[mods]]
modId="voxy"
version="${mod_version}"
displayName="Voxy"
authors="Cortex"
description='''
Far-distance LOD rendering mod (NeoForge port).
'''

[[mixins]]
config="common.voxy.mixins.json"

[[mixins]]
config="client.voxy.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.voxy]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="sodium"
type="required"
versionRange="[0.6,)"
ordering="BEFORE"
side="CLIENT"
